---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hqqqh7h7lc3p/public_html/test-prroperties
    - /bin/cp -R images $DEPLOYPATH
    ---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hqqqh7h7lc3p/public_html/test-prroperties
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH