@extends('saas.frontend.layouts.app')

@section('content')
<!DOCTYPE html>
<html>
<head>
    <title>Prroperties Investor Terms of Service</title>
    <style>
        /* Style for larger screens (desktops) */
        .responsive-heading {
            font-size: 24px; /* Default size for desktop */
            color: #333;
            font-family: Arial, sans-serif;
            margin-top: 130px;

            text-align: center; /* Center align the text */
        }

        /* Adjustments for smaller screens if needed */
        @media screen and (max-width: 1024px) {
            .responsive-heading {
                font-size: 20px;
            }
        }

        @media screen and (max-width: 768px) {
            .responsive-heading {
                font-size: 18px;
            }
        }

        @media screen and (max-width: 600px) {
            .responsive-heading {
                font-size: 16px;
            }
        }

        /* Centering the entire content */
        body {
            text-align: center;
        }
        
        
        .margin{
            
                        margin-bottom:50px;
        }
    </style>
</head>
<body>
    <h1 class="responsive-heading">Construction Service Provider Terms</h1>
   
    <p class="margin">Construction Service Provider Terms
Welcome to Trelegate! We’re excited to help you grow your business. When you use Trelegate, you enter into a legal agreement, which are the Terms that you see below. We have made an effort to make this agreement as clear and concise as possible, but we could not avoid including a certain amount of legalese. To help you understand the key provisions of this agreement, below this introduction we’ve included questions and answers that address the most important points of the agreement that you should understand. This summary is not part of the agreement itself, but rather a tool to help you better understand the agreement and the terms of your membership. You still need to read the entire agreement below! We have also bolded several areas that address important legal rights, including a class action waiver and binding arbitration.
IMPORTANT NOTICE: THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER. IT AFFECTS YOUR LEGAL RIGHTS AS DETAILED IN THE ARBITRATION AND CLASS ACTION WAIVER SECTION BELOW. PLEASE READ CAREFULLY.

Key Provisions of Your Trelegate Leads Membership
●Q. How does Trelegate work? A. First we find consumers looking for help with home projects and collect information about their project. Our patented ServiceProvider Finder technology then identifies relevant professionals, taking into account our pros' availability, service type and location preferences. When we have a match, we send the consumer's information to the matched pro(s) instantly so that he/she/they can contact the consumer (“a Lead”) to try and win the job . A Lead is NOT a guaranteed job but the contact information of an interested customer and the chance to sell a job. While all of the Leads that you pay for will not turn into won jobs, successful pros win more than enough jobs to return a profit and pay for the Leads that did not turn into won jobs .
●Q. What are the terms of payment? A. By signing your contract during enrollment (which is the formal process for accepting Trelegate's Terms), you are agreeing that once you pass your background check and are therefore approved, Trelegate can immediately begin charging your method of payment for membership and for lead fees.
●Q. Do I only pay for the jobs I win? A. No, Trelegate does not provide or guarantee jobs, and frequently a Lead is sent to several other pros, including to Trelegate and Handy themselves. You will be charged for each Lead you receive, whether or not you ultimately win the job, and regardless of whether the customer hires any pro to complete the job.
●Q. What are the types of Leads I may receive? A. The below are the current Lead types (additional opportunities may be available to you in Trelegate’s discretion):
Market Match: Auto accepted based upon the tasks and zips you have set up on your profile. Consumer is matched with pros, you receive Lead notification, with consumer contact info, job details, and number of other pros matched.
Exact Match: Auto accepted based upon the tasks and zips you have set up on your profile. Consumer chooses which pro to send their information to, Lead notification includes job details and consumer contact information.
Instant Booking: Auto accepted based upon the tasks and zips you have set up on your profile, consumers schedule jobs with you directly from your profile which is synced with your calendar.
Instant Connect: You choose to accept. A consumer requests to talk to a pro about their project, Trelegate immediately connects the consumer with you live on the phone. If you do not answer, we send the Lead to another pro.
Opportunity Lead: You choose to accept. Review and choose to accept/decline additional consumer requests you would have otherwise missed.
●Q. Can I turn off my Leads? A. You can turn off your Leads for a period of time, but once this time period is over they will automatically be turned back on and you will be charged for Leads received. If you pause or turn off your Leads, when you turn them back on, a new monthly spend target cycle may be created, such that it is possible your monthly spend target could be exceeded in less than one calendar month. Additionally, your exact spend target may be exceeded in the normal course of events for multiple reasons. You can opt out of Instant Booking Leads, Instant Connect Leads, and Opportunity Leads, but may not opt out of Market Match or Exact Match Leads. Please review your invoices regularly to ensure that you are satisfied with your spend target as set.
●Q. What is a spend target? A. Your spend target is an estimated 28 day amount that you would like Trelegate to try to meet when sending you Leads. The spend target is not a budget cap, but rather an estimated goal of monthly Lead spend, and will be allocated between Exact Match Leads and Market Match Leads.
●Q. Do all Leads count towards my spend target? A. No, Trelegate offers several types of highly targeted Leads that do not count towards your spend target. These include Instant Booking, Instant Connect, and Opportunity Leads. Market Match and Exact Match leads do count towards your spend target. Only Opportunity Leads and Instant Connect Leads must be individually accepted before your method of payment is charged.
●Q. How much do leads cost? A. The price of our Leads varies due to a number of factors, including the type of request and the location of the request. Once enrolled, you can see the current price of Leads for the tasks and areas for which you are profiled by logging into your Trelegate Pro account.
●Q. Do you warrant or guarantee your service? A. No, we do not make any warranties about our services, including whether you will be successful or how many jobs you will win.
●Q. How will you contact me? A. By becoming an Trelegate member, you authorize Trelegate and its affiliates to contact you regarding account information or other marketing offers via email, fax, text, or phone, using automated technology, even if you are on a state or federal Do Not Call list and even if you have previously opted out of Trelegate marketing.
●Q. What does it mean that I need to indemnify you? A. If someone sues us because of something you did, you're responsible for it, so please read Section 7 carefully.
●Q. What is arbitration, and what does it mean to waive my class action rights? A. A third party arbitrator will help us resolve any disputes we might have. This means that any dispute will be resolved outside of class-action litigation. Hopefully, disputes will never be an issue, but you should read Section 8 carefully for details on how it works.
●Q. Can I get a refund if I cancel my membership? A. You are entitled to a refund of fees paid if you cancel within seventy two (72) hours of enrolling, including fees paid for Leads you have not contacted. In any other case, Trelegate is not obligated to refund to you any fees.
●Q. How do I cancel my membership? A. You may cancel your membership by contacting Customer Care at (415) 212-5211, by emailing support@Trelegate.com, or by using live chat.
Trelegate SERVICE PROFESSIONAL TERMS

This Agreement ("Agreement") governs your relationship with Trelegate a California Limited Liability Company with the principal place of business 514 N. California Ave. Beaumont CA. In this Agreement, we will refer to you, the member Service Professional, and all of your d/b/a's, affiliates, agents, employees, representatives and subcontractors as "you," "SP," "Service Professional" or "member" and to Trelegate Leads and its employees and agents as "we" or "us" or "Trelegate." Other Service Professionals who have joined Trelegate's network are referred to in this Agreement as "Service Professionals," "SPs," or "members." Unless otherwise stated, all terms and conditions set forth in this Agreement that apply generally to Service Professionals also apply to and bind you. References herein to the Trelegate "Website" include any and all websites now, or hereafter, owned or operated by Trelegate, a Renesent, Inc. company. It is important to read our entire Agreement carefully as some of the provisions affect your legal rights. These Terms & Conditions were last updated on February 10, 2022.
1.What We Agree.


a.With Respect to Lead Purchasing Members.


i.Trelegate Leads receives requests from homeowners, consumers, property managers, individuals and other persons ("customers") expressing interest in certain services relating to home improvement, repair, maintenance and other types of tasks and projects ("service requests"). These service requests from customers may be submitted directly or indirectly to Trelegate Leads by customers via the Trelegate Leads Website, the Trelegate Ads Website, telephone calls, third party websites or other means. In turn, Trelegate Leads may send you a communication about a customer's service request that contains information about what service has been requested and the customer's contact information (a "Lead"). We may also send your contact information to the customer. The information we provide about you will be based on the information you submit during the Company Profile Interview (which you may amend from time to time) and Customer Ratings & Reviews, and may be amended by Trelegate Leads from time to time. Trelegate may also use masked tracking phone numbers, email addresses, or other methods of contact tracking. Leads may also be sent to other member service professionals based on the category of the service request.
ii.We limit the number of Service Professionals that are matched to a customer. We do not guarantee to provide you any specific number of Leads, nor do we make guarantees, representations or warranties regarding a customer's level of interest, their desire to have work completed, their ability to pay you, the accuracy of the information provided by the customers, or that any customers will hire you to perform services, nor do we guarantee that you will successfully contact each customer. You may also be competing against Trelegate Leads, or its affiliates and its affiliates' service professionals, including Trelegate Ads and Handy, for the job. We are not involved in, nor do we have any responsibility for your contracts with customers or any payments to you or any disputes they may have with you or you may have with them. Trelegate Leads is free to contract with other Service Professionals as this is not an exclusive contract.
iii.We provide customers with the ability to rate their experience working with you via Customer Ratings & Reviews. You will also have the ability to solicit and collect ratings and reviews from any of your customers, which may or may not be displayed in a Directory (defined below), in Trelegate Leads' sole discretion.
iv.For Service Professionals using Trelegate Leads' Exact Match Services (not available in Canada), Trelegate Leads shall endeavor to generate click-throughs to the SP's listing and online profile page and calls to the Exact Match Numbers (defined below), based upon the profile information supplied by SP. Trelegate Leads shall provide for the hosting of the SP online profile page (which may appear in the Trelegate Leads TheDirectory (defined below) and elsewhere on the Internet, however, SP is solely responsible for all content provided by SP that appears on SP's online profile page. Trelegate Leads shall provide the telephone numbers unique to SP's online profile page ("Exact Match Numbers"). In addition, customers will be able to complete a service request on the SP online profile page. A submission of a service request by a customer on SP's online profile page, or via a telephone call to SP's Exact Match Number shall constitute an "Exact Match Lead."
v.If your Trelegate Leads rating drops to three (3) stars or below, you will no longer be permitted to purchase leads from Trelegate Leads until you raise your rating above three (3) stars (although your directory listing will remain active). You will have the ability to improve your rating by acquiring additional positive reviews to lift the rating. However, you will not be able to use references from non-Trelegate Leads consumers to increase your rating, you must obtain additional consumer reviews submitted through the Trelegate Leads platform. Once your rating is greater than three stars, you will regain your eligibility to purchase leads.

b.With Respect to Subscription Members:

You may purchase a subscription to receive services including: Placement in Trelegate Leads's directory product which is displayed on the Trelegate Website ("TheDirectory") and Customer Ratings and Reviews solicitation. You may be displayed among service professionals who are members of Trelegate Leads affiliate companies, including Trelegate Ads, some of whom may have been subject to different screening criteria than the screening you are required to undergo.
In the event you purchase a subscription and elect to appear in the TheDirectory, your business listing may appear on the Pro Reviews section of the Trelegate Leads Website, in response to requests from customers for contractors in the project categories that you have indicated to us that you perform, in geographic locations where you have told us you perform services. Trelegate Leads does not make any representations or warranties regarding how often your listing and/or profile (including any ratings or reviews) will appear or be viewed, or where or on what page of the Pro Reviews tab your listing will appear, or your conversion rate for impressions or views of your profile page. You will also have the ability to solicit and collect ratings and reviews from any of your customers, which may or may not be displayed in TheDirectory, in Trelegate Leads's sole discretion. In addition, the telephone number displayed with your listing shall be your actual telephone number that you provide to Trelegate Leads (unless your listing is appearing as an Exact Match listing).
c.BILLING FOR SERVICE PROFESSIONALS ON BOTH Trelegate ADS AND Trelegate LEADS NETWORKS: If you are both an Trelegate Ads member and an Trelegate Leads member, you agree that you are receiving separate and valuable consideration from both Trelegate Leads and Trelegate Ads by way of Contacts, including Leads, and exposure to consumers of both platforms. While there are some overlapping benefits for advertisers on both networks, Trelegate Ads and Trelegate Leads are separate products and there is separate value in the products and services they offer to you.
2.What You Agree.

You agree to all terms and conditions of this Agreement and represent, on behalf of you, your company (including any predecessor entities of your company), employees, subcontractors, and any individuals performing work on your behalf, at the time you become a Trelegate Leads SP, and thereafter while this Agreement remains in effect, as follows:


a.Background Check Authorization and Disclosure:
i.AUTHORIZATION: You hereby: (a) represent that you are the owner, principal, or manager of the company with authority to bind the company; and (b) authorize Trelegate Leads to provide your home mailing address, social security number, date of birth ("Personal Information") and any other information you provide to us to a third-party information collection service entity selected by Trelegate Leads, at any time while your company is in Trelegate Leads’s network, to verify, obtain copies of records, and gather any information pertaining to your criminal record, as well as financial screening (including but not limited to searches for bankruptcies, liens and civil judgments) for the purpose of Trelegate Leads's evaluating its desire to enter into or continue a contractual business arrangement with you. Trelegate Leads will share this Personal Information only with third parties designated to carry out the background checks and with Trelegate Leads’s affiliates.
ii.DISCLOSURE: Trelegate Leads hereby discloses to you that a consumer report, as defined by the Fair Credit Reporting Act, may be obtained for the purpose of advertising with Trelegate Leads, its affiliates, representatives, or agents. You hereby authorize the procurement of the consumer report. Information from the consumer report will not be used in violation of any applicable federal, state, or local equal employment opportunity law or regulation. You understand that your date of birth will be used solely for identification purposes and will not be taken into account in any advertising decisions.
b.Membership in the Trelegate Leads network is available only to individuals who are at least 18 years old and can form legally binding contracts under applicable law. By applying to join Trelegate Leads, you represent and warrant that you are eligible.
c.You are qualified and capable of performing the services, trade, or tasks you selected on the Service Professional Enrollment Form or during your Company Profile Interview, and any subsequent amendments you make to your Customer Profile.
d.You are, and at all times will be, properly and fully licensed*, bonded and insured** (at levels in accordance with applicable industry standards) under all applicable laws and trade regulations (and upon request will produce documentation to verify this), and further, that you have not been turned down for insurance coverage related to your provision of services. You will notify us promptly of any such changes to your licensing, bonding or insured status.
*If you or your company are operating under a license with special restrictions you agree and represent that you will at all times operate within the guidelines as specified by such restrictions.
**This requirement is only applicable to service professionals accepting Leads in the "Movers" category.
e.You will comply with the Trelegate Leads membership requirements as specified from time to time. If these requirements are amended, you will be advised and must comply with any changes immediately upon notification if no action is required on your part or within thirty (30) days if affirmative action is required of you.
f.You hereby represent that you, any predecessor entities of your company, any other majority shareholders, partners or members, and your company, are free from any felony criminal convictions. If at any time during your membership with Trelegate Leads you, any predecessor entities of your company, any other majority shareholders, partners or members or your company, should have a felony conviction entered against such party, you will promptly notify Trelegate Leads. You further represent that you have not been sanctioned or penalized by any governmental authorities in connection with your provision of services to any of your customers, and that you have not been denied membership to (or had your membership revoked from) any professional industry associations. You authorize Trelegate Leads to verify that all of the above representations are truthful and accurate at any time while this Agreement remains in effect.
g.You further represent and warrant that you, your employees and subcontractors do not have any criminal dispositions in connection with any military service whether in or through a military court, military tribunal, or court martial. You further represent and warrant that neither you, your employees nor your subcontractors will be impaired by any drugs, alcohol or other controlled substances while performing any services pursuant to this Agreement.
h.You will cooperate with us if we attempt to facilitate the resolution of any customer complaints between you and your customers; however we are not liable to you or any customer if such matters cannot be resolved. We reserve the right to charge you for any amounts paid to a customer by Trelegate Leads in connection with a dispute between you and a customer, or based upon your performance of or failure to perform services for a customer, and you agree to reimburse us for any such payments and for any costs, expenses or attorneys' fees incurred by Trelegate Leads in connection with the dispute. You agree that we shall have the right to disclose any information we have regarding you and your company to any authorities requesting information from us regarding any work or services you have performed.
i.If you provide any quotes to customers via the Trelegate Leads Website, such quotes are provided for informational purposes only. A customer cannot contract with you via the Trelegate Leads Website. In the event a customer selects you on our Website in response to a quote you provide (or schedules and appointment), such selection (or appointment) is merely an indication of the customer's interest in contacting or being contacted by you. You agree that you will not charge a Lead fee to a consumer who has not hired you for a job.
j.If you provide written comments or testimonials about our service or activities, you agree that we shall have sole ownership of any and all intellectual property rights in such comments or testimonials, and that we may post and publish your comments or portions thereof at our sole discretion on our Website or in marketing materials including your name and company or agency, and that you shall not be entitled to any payments associated with our use of the foregoing. You hereby authorize us to use your name, company name, and franchise name, as applicable, and any of the trademarks, service marks, trade names and logos, content including photographs, in the form or format that you supply to us or that you upload to our Website, for use and posting on our Website and for use in marketing materials to be presented to customers or prospective SPs in online postings, via emails or otherwise to help promote you or your services, and that you shall not be entitled to any payments associated with our use of the foregoing. Trelegate Leads reserves the right, in its sole discretion, to review, reject and remove any content that you upload to the Trelegate Leads Website or your company profile. You further represent that you have all necessary rights to display any of the logos, service marks, trademarks, and any other content that you upload to our Website, and you represent that your uploading for display of any such content, and the use by Trelegate Leads of such content as contemplated by this Agreement, shall not violate any third party's intellectual property rights. If there are any limitations or restrictions pertaining to the use or presentation of such logos, trade or service marks, it shall be your responsibility to provide us in writing with any such restrictions or limitations of use. If expressly authorized by us in writing in advance, you may be authorized during the term of this Agreement to use certain marks of Trelegate Leads as necessary to promote your business. You are expressly prohibited from registering any trademarks or domain names of Trelegate Leads.
k.By posting or providing any content on the Trelegate Leads Website, including but not limited to photographs ("Content"), you represent and warrant to Trelegate Leads that you own or have all necessary rights to use the Content, and grant to Trelegate Leads the rights granted below. The forgoing representation includes, but is not limited to a representation and warranty that you have own or have the necessary rights (including any necessary releases) to grant all rights granted below in relation to any persons, places or intellectual property pictured in any photographic Content that you provide. In addition, if you post or otherwise provide any Content that is protected by copyright, you represent that you have obtained any necessary permissions or releases from the applicable copyright owner. You hereby grant Trelegate Leads and its users a perpetual, irrevocable, non-exclusive, royalty-free, transferable, assignable, sub-licensable, worldwide license to use, store, display, reproduce, modify, edit, abridge, crop, create derivative works, perform, distribute, and place advertising near and adjacent to your Content on the Trelegate Leads Website, and on any other websites owned or operated by Trelegate Leads. Nothing in this Agreement shall restrict other legal rights Trelegate Leads may have to the Content, for example under other licenses. Trelegate Leads reserves the right to remove or modify Content for any reason, including Content that Trelegate Leads believes violates this Agreement or our policies. You further authorize us and our affiliates, licensees, sublicensees, and users, without compensation to you or others, to reproduce, print, publish and disseminate in any format or media (whether now know or hereafter created) the Content, including, if submitted, your name, voice and likeness throughout the world, and such permission shall be perpetual and cannot be revoked for any reason. In the event your Trelegate Leads account is terminated, or if you remove any Content from your Trelegate Leads account, Trelegate Leads and its users may retain your Content and may continue to use any of your Content (pursuant to the license granted above). You acknowledge and agree that any Content you post or provide may be viewed by the general public and will not be treated as private, proprietary or confidential. Further, to the extent permitted under applicable law, you waive and release and covenant not to assert any moral rights that you may have in any Content posted or provided by you.
l.You acknowledge and agree that all of the content and information posted on the Trelegate Leads Website, including but not limited to Service Professional profiles, screening information, and Customer Ratings & Reviews for all Trelegate Leads Service Professional members (excluding any logos or trademarked materials, or other intellectual property of Service Professionals provided by Service Professionals), is the sole and exclusive property of Trelegate Leads. You acknowledge and agree that you have no right to reproduce, post, publish, display or otherwise use any Customer Ratings & Reviews (including those relating to you and your business), or any other content posted on the Trelegate Leads Website, other than content provided directly by you. You represent and warrant that all of the information you provide to Trelegate Leads, including any and all information you include on your profile page, is true and accurate. You acknowledge that a violation of any of the foregoing could result in significant damages, and you agree that you are liable to Trelegate Leads for any such damages, and will indemnify Trelegate Leads in the event of any third party claims against Trelegate Leads based on or arising from your violation of the foregoing. You acknowledge and agree that Trelegate Leads has the right, in its sole discretion, to contact customers about services you provide to gain their feedback and rating of you, and to display such Customer Ratings and Reviews on our Website. Trelegate Leads is not responsible or liable to you for any comments, ratings or communications of any kind from customers that we choose to post on our Website.
m.You will not engage in any illegal acts or acts of wrongdoing, dishonesty or unethical business practices with Trelegate Leads, any customer or other third party, including, but not limited to, disclosing any user personal information to any third party. You will at all times be in full compliance with all applicable Federal, State, Provincial, local and other laws and regulations that apply to your activities. YOU ACKNOWLEDGE AND AGREE THAT TO KNOWINGLY SHARE, DISTRIBUTE, TRANSFER, OR SELL A Trelegate LEADS SERVICE REQUEST, OR LEAD (OR THE INFORMATION CONTAINED THEREIN) OTHER THAN AS EXPRESSLY SET FORTH IN THIS AGREEMENT, IS A VERY SERIOUS BREACH OF CONTRACT AND FRAUDULENT MATTER THAT COULD RESULT IN INVASION OF PRIVACY RIGHTS OR OTHERS, SIGNIFICANT COSTS AND DAMAGES TO OTHERS AND TO Trelegate LEADS AND OTHER SERVICE PROFESSIONAL MEMBERS. RESPONDING TO SUCH A VIOLATION WOULD ALSO RESULT IN THE LOSS OF TIME AND EFFORT ON THE PART OF Trelegate LEADS. THERE ALSO MAY BE REGULATORY FINES AND PENALTIES IMPOSED FOR CONTACTING CONSUMERS AND BUSINESSES IN A MANNER NOT IN ACCORDANCE WITH THE APPLICABLE LAWS AND REGULATIONS INCLUDING BUT NOT LIMITED TO FEDERAL STATE AND PROVINCIAL DO-NOT-CALL REGULATIONS AND FEDERAL STATE AND PROVINCIAL ANTI-SPAM REGULATIONS. ACCORDINGLY, IF YOU KNOWINGLY SHARE, DISTRIBUTE, TRANSFER, OR SELL A SERVICE REQUEST, OR LEAD (OR THE INFORMATION CONTAINED THEREIN) OTHER THAN AS EXPRESSLY SET FORTH IN THIS AGREEMENT, YOU AGREE TO FULLY INDEMNIFY AND BE LIABLE TO Trelegate LEADS, AS SET FORTH IN SECTION IV BELOW, FOR ALL THE DAMAGES, WHETHER DIRECT OR INDIRECT, PUNITIVE AND CONSEQUENTIAL, AND ANY REGULATORY OR JUDICIAL FINES OR PENALTIES OR ATTORNEYS' FEES THAT MAY ARISE FROM SUCH ACTIVITIES.
n.You agree to allow only employees of your company or independent contractors performing services directly on behalf of your business to contact or provide any service to customers you learn of via a Lead. To the extent you use any such subcontractors, you shall be responsible and liable for all acts and omissions of such subcontractors and for ensuring that such subcontractors comply with all the provisions of Section II of this Agreement. You agree not to sell, trade, gift, assign, or otherwise transfer any Service Requests, or Leads provided by Trelegate Leads to any other party, including any other Trelegate Leads Service Professionals.
o.In addition to all of the other terms and conditions herein, SPs using Trelegate Leads's Exact Match services (not available in Canada) also agree to the following: (i) SP hereby represents and warrants that the information provided by SP in the SP profile on the SP's online profile page is, and shall at all times be, maintained in an accurate, up-to-date and professional manner, and in compliance with all applicable laws and regulations; (ii) SP hereby agrees that it hereby has automatically pre-accepted any Exact Match Leads provided to it by Trelegate Leads; (iii) SP hereby agrees to pay for any and all Exact Match Leads, in accordance with the then current Trelegate Leads fee schedule; (iv) Trelegate Leads may provide SP's phone number to any individual calling the Exact Match Numbers; (v) SP acknowledges and agrees that not all consumers calling the SP's Exact Match Number or visiting the SP's online profile page will be directed to SP for reasons including, but not limited to the Exact Match consumer's request not matching the SP's profile, SP's account being on hold or no longer being a member of the Trelegate Leads network, or the SP not having any available spend target. In such event, Trelegate Leads may direct consumers from the SP's online profile page to the Trelegate Leads Website; (vi) SP hereby authorizes Trelegate Leads to take any and all actions necessary to generate click-throughs to SP's online profile page and telephone calls to Exact Match Numbers, including contracting with search engines, Internet directories, and other online and offline advertising sources and making the representations herein on behalf of SP to such third parties, and (vii) SP authorizes Trelegate Leads to use, copy, reproduce, and sublicense SP's contact information, SP's profile, and any content on the SP's online profile page in furtherance of the foregoing. You further acknowledge, that in the event you are using Trelegate Leads's Exact Match services, and you are also a TheDirectory subscription member, you may appear in the TheDirectory at different times as an Exact Match listing, or a TheDirectory subscription member listing, but will only be charged Lead Fees when you receive a service request generated from your listing appearing as an Exact Match listing.
p.In the event you participate in any promotion whereby Trelegate Leads promotes an offer or discount related to your services, whether on the Trelegate Leads Website, via direct mail, or otherwise, you agree to abide by the terms of such offer or discount.
q.By enrolling in the Trelegate Leads network or otherwise becoming a member of Trelegate Leads, and/or by inquiring about membership in the Trelegate Leads network or other Trelegate Leads products or services, you are requesting, and you expressly consent to being contacted by us and by our agents and representatives via phone, fax, email, mail or other reasonable means, at any of your contact numbers or addresses, even if you are listed on any federal, state, provincial or other applicable "Do Not Call" list, and even if you have previously opted-out from receiving marketing emails from Trelegate Leads, in order that we may provide the services set forth on our site, to service your account, to reasonably address matters pertaining to your account or for other purposes reasonably related to our business, including marketing related emails. You agree and acknowledge that Trelegate Leads and its affiliates may use automated phone technology (including autodialed and prerecorded messages) to provide you with operational communications concerning your account or use of the Services, updates concerning new and existing features on the Trelegate Leads website, communications concerning promotions run by us, and news concerning Trelegate Leads and industry developments, and that your consent is not required to purchase products or services. If a contact number you have provided to us is no longer your number, you agree to notify us promptly that you can no longer be reached at that number. You represent that you have received, and are authorized to convey to us, the consent of any authorized users on your account to be contacted by us as described in this Section. You agree that all consents provided in this Section will survive cancellation of your account. You consent to be automatically opted in to Trelegate Leads’s SMS program, “Trelegate Leads Alerts,” and agree that Trelegate Leads may send you text messages with instructions on setting up your account and special offers. For questions, Text HELP for more help or call (415)- 212-5211, and Text STOP to opt out of messages. Message and data rates may apply, and message frequency may vary. Carriers are not liable for delayed or undelivered messages, and supporting carriers include AT&T, Sprint, Verizon, T-Mobile & Metro-PCS. You may opt-out of receiving all text (SMS) messages from Trelegate Leads (including informational or transactional messages) by replying with the word "STOP" to a text message from us; however you acknowledge that opting out of receiving all texts may impact your use of the Services.
r.Trelegate Leads's mobile applications may implement location features that, if you consent, result in automatic collection of your geolocation information, in which case our mobile application may use such information to allow Trelegate Leads and customers to view and track your location. We may also use this location information for our internal business purposes, and for providing and enhancing our products and services and advertising. IF YOU WANT TO STOP THE AUTOMATIC COLLECTION OF YOUR LOCATION INFORMATION, YOU MAY DO SO BY USING THE PRIVACY SETTINGS ON YOUR DEVICE, OR BY UNINSTALLING OUR MOBILE APPLICATION. CERTAIN FEATURES, SUCH AS SAME DAY SERVICE, WILL NOT BE AVAILABLE IF YOU OPT OUT OF LOCATION COLLECTION.
s.You represent and warrant that to the extent that a consumer is interested in any financing options, you will direct them to Trelegate Leads, and you will not attempt to apply for any financing on the consumer's behalf, or make any representations to the consumer regarding financing options or the likelihood of a consumer being approved for financing.
3.Fees.

a.You agree to be bound by the then applicable pricing plan provisions (all fees are stated and payable in US dollars) for any and all Leads presented to you , or for any inclusion in our TheDirectory service or any other subscription offering. Trelegate Leads reserves the right to charge your method of payment for any fees immediately upon receipt of your payment information by you or your representatives.


i.Lead Fees. You agree that you will pay Trelegate Leads on a per Lead basis for all Leads. You may view a statement of your monthly Lead activity on your Trelegate Leads account, at pro.Trelegate.com or in the Trelegate Pro App. We may, in our sole discretion and in accordance with our then-existing Lead credit policies, located at https://Trelegatex.com/#leadcredit, issue you a credit ("Credit") for any Lead Fees that you dispute (by contacting Trelegate Leads via our Website, the Trelegate Leads Pro app, or by telephone), provided, however, that any and all requests for Credits must be received by Trelegate Leads within 45 days of the date that the Lead Fee charge was incurred. Credits that are issued to a Service Professional's account will be issued as store credits, which will be applied toward future charges to your account. Credits will expire, if not used, eighteen months after the date the Credit was issued. All Lead Fees constitute advertising fees paid by you to Trelegate Leads and are in no way, referral commissions based upon your successful completion of services.
ii.Subscription Fees; License Fees; Other Recurring Fees.

For purchases of a subscription membership (monthly, quarterly, or annually), you shall pay such fees on a monthly, quarterly or annual basis, as applicable. You agree that payments will be made by Trelegate Leads initiating an ACH transfer or processing your credit card, in advance, on a monthly, quarterly or annual basis, as applicable.
i.AUTOMATIC RENEWAL OF SUBSCRIPTION; After your initial subscription period, and again after any subsequent subscription period, your subscription will automatically continue for an additional equivalent period (each a "Renewal Term"), at the renewal price communicated to you at the time your purchased your initial subscription ("Renewal Price"), unless Trelegate Leads provides you with at least thirty (30) days advance notice of a change in your Renewal Price. You agree that your account will be subject to this automatic renewal feature. If you want to change or terminate your subscription, you may do so solely by contacting Trelegate Leads Customer Care at (415) 212-5211. If you cancel your subscription, you may use your subscription until the end of your then-current subscription term; your subscription will not be renewed after your then-current term expires, and you won't be eligible for any refund of any portion of the subscription fee paid for the then-current subscription period. By subscribing, you authorize Trelegate Leads to charge your provided payment method now and again at the beginning of any Renewal Term. You also authorize Trelegate Leads to charge you for any sales or similar taxes that may be imposed on your subscription payments. Upon the renewal of your subscription, if Trelegate Leads does not receive payment from your payment method or payment method provider, (i) you agree to pay all amounts due on your account upon demand, and/or (ii) you agree that Trelegate Leads may either terminate or suspend your subscription and continue to attempt to charge your payment method until payment is received.
ii.Free Trials and Other Promotions. Any free trial or other promotion that provides a subscription to the Trelegate Leads services automatically renews in the same manner as set forth above under the section titled "Automatic Renewal", provided, however, that the Renewal Price for any Renewal Terms will be higher than during the free trial or promotion initial term. You must cancel your subscription before the end of the trial period in order to avoid being charged the Renewal Price.
iii.Discounts. When you purchase multiple products, you may be eligible for certain discounts, as set forth on the then-current pricing plan, provided, however, that cancellation of a product/service for which you have received a discount, may result in the discount being rescinded retroactively for the remaining products/services, and an immediate additional payment to be charged to your method of payment. Purchases of prepaid Lead bundles are nonrefundable, even after cancellation of membership.
iii.You acknowledge that it is your responsibility to ensure that the communication methods that you have selected in your Trelegate Leads profile, and all contact and billing information, are kept up-to-date and accurate. Trelegate Leads is not responsible, or liable, for undelivered customer notifications. You agree to promptly notify Trelegate Leads if your payment method is canceled (including if you lose your card or it is stolen), or if you become aware of a potential breach of security (such as an unauthorized disclosure or use of your payment method). In addition, you authorize us to obtain updated or replacement expiration dates and card numbers for you credit or debit card as provided by your credit or debit card issuer.
iv.You acknowledge that you will not receive a detailed account statement unless you provide Trelegate Leads with a valid email address or fax number. Your account balance is also available by calling (415) 212-5211 or via the Account tab of the Pro.Trelegate Leads.com Website. Trelegate Leads will process your balance due at the end of your billing period via your selected payment method. Past due balances will be subject to a late charge equal to the lesser of 1.5% per month or the maximum amount allowed by applicable law. In addition, any returned payments will incur a $20 fee per transaction.
v.Any disputes about charges to your account must be submitted to Trelegate Leads in writing within 30 days of the date such charges are incurred. You agree to waive all disputes not made within the 30 day period, and all such charges will be final and not subject to challenge.
vi.Past due accounts may be turned over to a third-party collection agency and reported to a credit rating agency and we may bill you for, and you agree to pay for any and all collection and related litigation fees.
vii.No fee is due or payable to the extent such fee is in violation of any applicable law.
viii.Trelegate Leads is not obligated to refund to you any amounts of prepaid Lead Fees or other prepaid fees such as subscription fees, except solely in the event you rescind or terminate your subscription within the seventy two (72) hour period following your agreement to purchase a subscription.
ix.You authorize Trelegate Leads to charge you for any sales or similar taxes that may be imposed on your subscription payments, Lead fees, or any other fees charged by Trelegate Leads.
4.Trelegate Pay
a.When a project has been completed, you may be offered the ability to receive your payment from the consumer directly via the Trelegate Leads mobile application (“Trelegate Pay”) in one of two ways, either by you requesting payment from a consumer, or by a consumer initiating payment to you. To request payment, you log into your Trelegate Leads App, go to your Lead Details, and click request payment for the appropriate Lead. If a consumer has sent you money for services, you will be able to log into your Trelegate Leads App, select how you wish to be paid (either to your bank account or to a debit card), and the payment will be processed promptly. You will have sixty (60) days after the consumer submits a payment to collect the payment. Should you opt out of Trelegate Pay (by going to Settings in your App, clicking the Trelegate Pay section and selecting Disable Trelegate Pay) or fail to collect your payment within this sixty day period, you and the consumer will be notified that the payment has been cancelled, and you will need to seek payment from the consumer directly. Trelegate Pay may not be used to charge a Lead fee to a consumer, it may only be used for collecting payment for a won job.
b.By participating in Trelegate Pay and agreeing to the Trelegate Leads Terms, you agree that you are accepting payments from Trelegate Leads consumers via Trelegate Pay and that Trelegate Leads is authorized to store your bank account or debit card information for future payments, and that Trelegate Leads may deposit all future payments into your Trelegate Pay account. You further agree that you will not seek payment from the consumer directly where you have received payment from the consumer through Trelegate Pay, and that you will only seek payment for services you have performed or will perform.
c.Trelegate Leads, in its sole and absolute discretion, may refuse to approve or may terminate existing enrollments for Trelegate Pay with or without cause or notice, other than any notice required by any applicable law, and not waived herein. Trelegate Leads may ban you from using Trelegate Pay (and the Trelegate Leads services) if we believe you are abusing Trelegate Pay. Trelegate Leads may also cancel a payment request made through Trelegate Pay if such request is improper in Trelegate Leads's reasonable commercial discretion.
d.You acknowledge and agree that your payments made through Trelegate Pay are transactions between you and the consumer and not with Trelegate Leads or any of its affiliates. Trelegate Leads is not a party to your payments unless expressly designated as such on the Trelegate Leads website.
e.Trelegate Pay may not be used to process a payment, or otherwise transfer money between you and a consumer, that is unrelated to the consumer’s purchase of services from you. You may not use Trelegate Pay to purchase any illegal goods or services or for any other underlying illegal transaction. You agree that you will not use Trelegate Pay to purchase any services or products that violate these Terms, other policies or rules applicable to Trelegate Pay, or applicable law. Failure to comply with these limitations may result in suspension or termination of your use of Trelegate Pay and/or your Trelegate Leads account.
f.You agree to release Trelegate Leads, its affiliates, and their agents, contractors, officers and employees, from all claims, demands and damages (actual and consequential) arising out of or in any way connected with a dispute related to Trelegate Pay. You agree that you will not involve Trelegate Leads in any litigation or other dispute arising out of or related to any transaction, agreement, or arrangement in connection with Trelegate Pay. If you attempt to do so, (i) you shall pay all costs and attorneys' fees of Trelegate Leads and its affiliates and shall provide indemnification as set forth below, and (ii) the jurisdiction for any such litigation or dispute shall be limited as set forth in Section X. However, nothing in these Terms waives any rights, claims or defenses that you may have with respect to a payment under an agreement with your method of payment issuer, the card association rules or applicable state and federal laws.
g.Payment processing services for Service Professionals are provided by Stripe and are subject to the Stripe Connected Account Agreement, located at https://stripe.com/us/connect-account/legal, which includes the Stripe Terms of Service, located at https://stripe.com/us/legal (collectively, the Stripe Services Agreement). By agreeing to these Terms herein, you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of participating in Trelegate Pay through Stripe, you agree to provide Trelegate Leads accurate and complete information about you and your business, and you authorize Trelegate Leads to share it and transaction information related to your use of the payment processing services provided by Stripe. You also authorize Trelegate Leads to pass on information provided by you (e.g. your birthday or the last four digits of your social security number) to Stripe so that Stripe may use it to protect the integrity of your account.
h.While we will use commercially reasonable efforts to ensure the security of all credit card and all other personal information, we expressly disclaim any liability for any damage that may result should any information be released to any third parties, and you agree to hold us harmless for any damages that may result therefrom.
i.If we determine that your actions or performance may result in returns, chargebacks, claims, disputes, violations of our terms or policies, or other risks to Trelegate Leads or third parties, or any payments to consumers that Trelegate Leads makes, then Trelegate Leads may either charge your method of payment on file with us for such payments, or withhold any payments to you for as long as we determine any related risks to Trelegate Leads or third parties persist. For any amounts that we determine you owe us, we may (i) immediately charge your method of payment; (ii) offset any amounts that are payable by you to us (in reimbursement or otherwise) against any payments we may make to you or amounts we may owe you; (iii) invoice you for amounts due to us, in which case you will pay the invoiced amounts upon receipt; (iv) reverse any credits to your bank account; or (v) collect payment or reimbursement from you by any other lawful means.
5.Trelegate Leads Seal of Approval. While this Agreement remains in effect, and while you remain in full compliance with all terms set forth herein, Trelegate Leads hereby grants you a non-exclusive, non-transferrable, non-sublicenseable, license to use and display the Trelegate Leads Seal of Approval in connection with marketing your business. You agree that any use or display of the Trelegate Leads Seal of Approval must comply with all standards and guidelines of Trelegate Leads adopted from time to time with respect to the proper use and display of the Trelegate Leads Seal of Approval.
a.Restrictions. You may only use the Trelegate Leads Seal of Approval in the event you pass Trelegate Leads's pre-screening criteria initially and annually thereafter, which shall be determined in Trelegate Leads's sole discretion. Trelegate Leads may also re-screen your business at any time in its sole discretion, and may terminate this Agreement in Trelegate Leads's sole discretion. Further, you agree that you will use and display the Trelegate Leads Seal of Approval solely in connection with the tasks for which Trelegate Leads pre-screens you. For example, if you are pre-screened as a plumber, you may not use the Trelegate Leads Seal of Approval to advertise your business for any services other than plumbing services. Further, you may only use the Trelegate Leads Seal of Approval in the state or states for which you have been pre-screened by Trelegate Leads. You may only use the Trelegate Leads Seal of Approval for its intended use, and you may not misrepresent Trelegate Leads, Trelegate Leads's products or Services, your affiliation with Trelegate Leads, or the Trelegate Leads Seal of Approval. If at any time any of your screening status should change (i.e. state-level license terminated; fall out of good standing in your state of incorporation), you must immediately report such change to Trelegate Leads, and if such change causes your business to fail Trelegate Leads's screening criteria, in Trelegate Leads's sole discretion, then your license to use the Trelegate Leads Seal of Approval is immediately suspended, and if not remedied to Trelegate Leads's satisfaction within thirty days of notification, this Agreement shall automatically terminate. You also hereby agree to be re-screened by Trelegate Leads annually, and at any other time as desired by Trelegate Leads, and failure to allow such rescreening, or failing the re-screening, in Trelegate Leads's sole discretion, shall result in the immediate and automatic termination of this Agreement. The license granted hereunder is solely for the use of the Trelegate Leads Seal of Approval, and you do not have any right to use the Trelegate Leads name or logo separately or apart from the Trelegate Leads Seal of Approval.
b.Accessing the Trelegate Leads Seal of Approval. You agree that you shall access the Trelegate Leads Seal of Approval solely via the following methods: (a) via a code snippet provided to you by Trelegate Leads for use online on your website, or (b) any other method generally offered by Trelegate Leads. You may not make any changes or modifications to the Trelegate Leads Seal of Approval (including the code snippet), and shall only use the Trelegate Leads Seal of Approval in the exact form and format in which it is provided to you by Trelegate Leads.
c.Review Generation. If you purchase a Professional Website, you will have the ability, via our "Review Generation" functionality, to select certain of your Trelegate Leads consumer Ratings & Reviews from your Trelegate Leads profile page, to be displayed on your Professional Website. Trelegate Leads authorizes you to use the Review Generation functionality, and display such Ratings & Reviews on your Professional Website solely while you remain an active member, in good standing, of the Trelegate Leads network. If at any time your membership in the Trelegate Leads network is terminated, by either you or Trelegate Leads, you shall no longer be authorized to display such Ratings & Reviews on your Professional Website, and you agree to remove all such Ratings & Reviews immediately.
6.Leads Outside of Spend Target

a.Instant Booking. Unless you expressly opt-out, Trelegate Leads may send you booked leads under Trelegate Leads's Instant Booking program ("Instant Booking"), which allows consumers to book appointments with you, on a calendar set up for you on the Trelegate Leads Website ("Booked Appointments"). You may choose to sync your own online calendar with the Trelegate Leads Instant Booking calendar so that these bookings will show up in real-time on your own calendar. We will notify you and attempt to confirm these bookings with you, so if you choose not to sync with the Trelegate Leads calendar, we recommend that you log in to your Trelegate Leads account and update the Trelegate Leads calendar to block out dates and times when you are not available or do not wish to book appointments. As part of Instant Booking, you agree to the following: (i) you shall update, maintain, and keep current your schedule in the Trelegate Leads Online Calendar (or any other calendar with which Trelegate Leads has integrated), (ii) you will confirm every Booked Appointment, provided, however, that you shall be charged for all Booked Appointments, regardless of whether you confirm them or not, (iii) you shall honor every Booked Appointment, show up on time for all such appointments, and honor any quotes or estimates you provide to consumers, (iv) you shall pay a premium lead fee for Booked Appointments (v) you understand and agree that Booked Appointments are not guaranteed jobs, but merely consumer leads, and that you are obligated to pay the applicable lead fees regardless of whether the consumer hires you, or even shows up for, or cancels, the booked appointment, (vi) lead fees for Booked Appointments are in addition to, and do not count toward, your spend targets for Leads, and therefore, if you have reached your spend target, you would still be charged for any Booked Appointments received thereafter. Trelegate Leads reserves the right to terminate your participation in Instant Booking at any time, for any reason or no reason.
b.Instant Connect. Trelegate Leads may offer you the opportunity to participate in Trelegate Leads's Instant Connect program ("Instant Connect"), which allows consumers to request to be connected to you directly via telephone. If you participate in Instant Connect, you agree to the following: (i) you shall pay a premium Lead fee for Instant Connect leads, (ii) you understand and agree that Instant Connect Leads are not guaranteed jobs, but merely consumer Leads, and that you are obligated to pay the applicable Lead fees regardless of whether the consumer hires you, (iii) Lead fees for Instant Connect are in addition to, and do not count toward, your spend targets for Leads, and therefore, if you have reached your spend target, you would still be charged for any Instant Connect Leads received thereafter. Trelegate Leads reserves the right to terminate your participation in Instant Connect at any time, for any reason or no reason.
c.Opportunity Leads. Trelegate Leads may offer you the opportunity to participate in Trelegate Leads's Opportunity Leads Program, which allows you to view and select additional job opportunities (consumer leads) submitted by consumers that may be outside of your selected zip codes. If you accept an Opportunity Lead, you agree to the following: (i) you shall pay a premium Lead fee for Opportunity Leads, (ii) you understand and agree that Opportunity Leads are not guaranteed jobs, but merely consumer Leads, and that you are obligated to pay the applicable Lead fees regardless of whether the consumer hires you, (iii) Lead fees for Opportunity Leads are in addition to, and do not count toward, your spend targets for Leads, and therefore, if you have reached your spend target, you would still be charged for any Opportunity Leads you have accepted thereafter, (iv) you must have the latest version of the Trelegate Leads mobile application to receive Opportunity Leads, (v) even if you have turned your Leads off, if you select an Opportunity Lead, you will be charged for that Lead, and (vi) you understand that Opportunity Leads are not exclusive to you and may also be sent to other service professionals. Elite members and/or members enrolled in Trelegate Leads under a corporate membership account are not eligible to participate in the Opportunity Leads Program.
d.Miscellaneous. Your spend target may be exceeded if you are experiencing high demand and you lower your spend target, because only the remainder of the 28-day period from when the spend target was changed will be managed by the new prorated spend target. Additionally, your exact spend target may be exceeded in the normal course of events by one Lead because our matching algorithm will send a Lead up until the precise point your spend target is exceeded (i.e. if your spend target is $500, and you are currently at $480, you may still receive at Lead valued at $40, at which point you would not receive any more Leads as you would have exceeded $500).
7.Indemnification; Limitation of Liability; Disclaimer of Warranties.

a.Indemnification. You shall fully protect, indemnify and defend Trelegate Leads and all of its agents, officers, directors, shareholders, suppliers, partners, employees and each of their successors and assigns ("Indemnified Parties") and hold each of them harmless from and against any and all claims, demands, liens, damages, causes of action, liabilities of any and every nature whatsoever, including but not limited to personal injury, intellectual property infringement, fraud, deceptive advertising, violation of any state, provincial or federal laws or regulations, property damage, attorneys' fees and court costs, arising in any manner, directly or indirectly, out of or in connection with or in the course of or incidental to (i) any of your work for or dealings with any customers, (ii) your advertising, or (iii) your services, representations, or obligations (including but not limited to your obligation to maintain the confidentiality of user personal information) set forth in this Agreement, including any extra work you perform for a customer for which Trelegate Leads has not matched you, and in connection with your use of the Trelegate Leads Seal of Approval, REGARDLESS OF CAUSE OR OF ANY FAULT OR NEGLIGENCE OF Trelegate LEADS OR THE INDEMNIFIED PARTIES AND WITHOUT REGARD TO CAUSE OR TO ANY CONCURRENT OR CONTRIBUTING FAULT, STRING LIABILITY OR NEGLIGENCE, WHETHER SOLE, JOINT OR CONCURRENT, ACTIVE OR PASSIVE BY Trelegate LEADS OR THE INDEMNIFIED PARTIES.
i.Limitation of Liability. IN NO EVENT ARE WE LIABLE TO YOU FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, PUNITIVE OR SPECIAL DAMAGES, LOST REVENUE, LOST PROFITS OR LOSS OF GOODWILL. IN NO EVENT WILL THE TOTAL AGGREGATE LIABILITY OF Trelegate LEADS TO YOU EXCEED THE AMOUNT OF FEES ACTUALLY PAID BY YOU TO Trelegate LEADS DURING THE PRECEEDING 12 MONTHS, REGARDLESS OF THE BASIS OR FORM OF CLAIM
ii.Disclaimer of Warranties. YOU ACKNOWLEDGE AND AGREE THAT THE Trelegate LEADS SERVICES AND Trelegate LEADS SEAL OF APPROVAL ARE PROVIDED TO YOU ON AN "AS IS" BASIS, AND Trelegate LEADS DISCLAIMS ANY AND ALL EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY LAW
8.AGREEMENT TO ARBITRATE ALL DISPUTES AND GOVERNING LAW.
a.The exclusive means of resolving any dispute between you and Trelegate Leads or any claim or controversy arising out of or relating to or that have arisen based on use of this Website and/or Trelegate Leads's services (including any alleged breach of these Terms and Conditions) shall be BINDING ARBITRATION administered by the American Arbitration Association, EXCEPT AS EXPRESSLY PROVIDED BY APPLICABLE FEDERAL OR STATE LAW. You may not under any circumstances commence, participate in or maintain against Trelegate Leads any class action, class arbitration, or other representative action or proceeding.

*NOTICE OF RIGHTS*
b.By using the Website and/or Trelegate Leads's services in any manner, you agree to the above arbitration agreement. In doing so, YOU GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend any claims between you and Trelegate Leads. YOU ALSO GIVE UP YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION OR OTHER CLASS PROCEEDING. Your rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY. You are entitled to a fair hearing before the arbitrator. The arbitrator can grant any relief that a court can, but you should note that arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.


i.Any proceeding to enforce this arbitration agreement, including any proceeding to confirm, modify, or vacate an arbitration award, may be commenced in any court of competent jurisdiction. In the event that this arbitration agreement is for any reason held to be unenforceable, any litigation against Trelegate Leads may be commenced only in the federal or state courts located in Riverside County, California. You hereby irrevocably consent to the jurisdiction of those courts for such purposes.
ii.These Terms and Conditions, and any dispute between you and Trelegate Leads, shall be governed by the laws of the state of Florida without regard to principles of conflicts of law, provided that this arbitration agreement shall be governed by the Federal Arbitration Act.
9.Other Terms.

a.This Agreement, and the Trelegate Leads fees, including Lead prices, may be changed from time to time. By continuing to use any Trelegate Leads services you are agreeing to be bound by any such non-material changes. Material changes to this Agreement will be posted on the Trelegate Leads Website at pro.Trelegate Leads.com/terms/terms-conditions/ and periodically communicated to you by email, text, the Trelegate Leads Pro app or other reasonable means. By continuing to use any Trelegate Leads services after receiving any such notice of changes from Trelegate Leads, you are agreeing to all such changes.


i.You may terminate this Agreement upon our receipt of your notice during normal business hours (such termination to be effective upon the close of business on the day properly delivered and received), but you shall be obligated to pay for any Leads or services delivered to you prior to us receiving your termination during normal business hours.
ii.Trelegate Leads, in its sole discretion, reserves the right to suspend your rights under this Agreement or terminate this Agreement and your membership in the Trelegate Leads network immediately at any time for any reason or no reason at all.
iii.If this Agreement is terminated or expires, your agreements and obligations under this Agreement shall continue; and any Leads provided to you during the term of this Agreement and relationships you enter into or create from those Leads will continue to be governed by this Agreement including but not limited to with respect to any disputes that may arise or claims that may be made against us and any indemnification of us by you for such claims. Further, in the event this Agreement is terminated or expires, (i) all licenses granted to you under this Agreement shall immediately terminate, and you shall have no further right to access, use or display the any Trelegate Leads content, including but not limited to the Trelegate Leads Seal of Approval in any manner, and (ii) you agree to destroy any materials containing the Trelegate Leads Seal of Approval. Upon any termination of this Agreement, you will no longer have access to your Trelegate Leads account.
iv.If it is determined or suspected by Trelegate Leads in its sole discretion that you are misusing or attempting to misuse or circumvent the Trelegate Leads services or system or any customer data, or are using or attempting to use it for any inappropriate, illegal, harmful, or anti-competitive, purposes, including but not limited to activities such as hacking, infiltrating, fraud, advertising, jamming or spamming, or any activities inconsistent with the services proposed to be offered by Trelegate Leads, in addition to our right to immediately terminate this Agreement, Trelegate Leads reserves the right, in its sole discretion, to instigate, without notice, appropriate legal actions or proceedings to seek appropriate remedies and/or damages, including but not limited to lost revenue, repairs, legal fees, costs and expenses, and to seek injunctions or other equitable remedies.
v.In the event of termination of this Agreement, except as set forth in Section 3 herein, you shall not be entitled to any refund of any fees paid to us, including any prepayments.
vi.You will be liable for any attorneys' fees and costs if we have to take any legal action (including the retention of a lawyer) to enforce this Agreement. The laws of the State of Florida (excluding the laws and principles with respect to conflicts of law) govern this Agreement. You hereby consent and agree that the state or federal courts in Broward Florida are the exclusive forum for litigation of any claim by you arising under this Agreement or your use of the Trelegate Leads Website and/or Services, and you submit to sole and exclusive jurisdiction in the state of Florida, and hereby irrevocably waive and relinquish any right to bring, or cause to be brought, any such action, or to have any such action brought, in any judicial or administrative forum outside of such forum.
vii.You understand and agree that you are an independent contractor of Trelegate Leads, and are not a Trelegate Leads employee, joint venturer, partner, or agent. You acknowledge that you set or confirm your own prices, provide your own equipment, and determine your own work schedule. Trelegate Leads does not control, and has no right to control, the services you provide (including how you provide such services) if you are engaged by a consumer, except as specifically noted herein.
viii.If any provision of this Agreement is held by any court or other authority of competent jurisdiction to be invalid, illegal or in conflict with any applicable state or federal law or regulation, such law or regulation shall control, to the extent of such conflict, without affecting the remainder of this Agreement.
ix.Wireless data usage is subject to the fees and terms of your wireless subscriber agreement or data service plan with your provider, and you may incur charges from your telephone service provider for text messages, phone calls, email communications and data transferred.
x.Trelegate Leads and its affiliates may view, store, access and disclose messages exchanged between you and consumers transmitted via Trelegate Leads's messaging platform or Trelegate Leads' website.
xi.Trelegate Leads has the right to use all information related to You in accordance with its Privacy Policy, which can be found at https://legal.Trelegatex.com/#privacy-policy
xii.You agree not to copy/collect Trelegate Leads content via robots, spiders, scripts, scrapers, crawlers, or any automated or manual equivalent (e.g., by hand).</p>
    
    
</body>
</html>


<!-- End homec Hero -->
@endsection
